---
AllCops:
  TargetRubyVersion: 2.6
  NewCops: enable
  Exclude:
    - db/schema.rb
    - 'node_modules/**/*'
    - 'vendor/**/*'
    - '.git/**/*'
    - 'bin/*'

Style/FrozenStringLiteralComment:
  EnforcedStyle: never

Layout/LineLength:
  Max: 120

Style/ClassAndModuleChildren:
  EnforcedStyle: compact

Metrics/BlockLength:
  Max: 35
