name: Build & Publish Ruby Gem

on:
  push:
  release:
    types: [created]

jobs:
  build:
    name: Build + Publish
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Publish to GitHub Packages
      uses: jstastny/publish-gem-to-github@master
      env:
        GEM_HOST_API_KEY: ${{ secrets.GITHUB_TOKEN }}
        OWNER: MikeRogers0
